### ISSUE TITLE
Display images for artist directories

### ISSUE THREAD

**Issue by orontee** [orontee/argos#143]
## TODO

- [ ] Add model for artist
- [ ] Extend `InformationService` to identify image URL from Wikidata for a given Musicbrainz identifier for an artist
- [ ] Download and display artist image

## Code cleanup

Move artist information from album model to the artist model.

**Comment by orontee** [comment]
Work in progress, confusion between "artist" and "directory" in current model...
